apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./deployment.yml

commonLabels:
  author: loadtest

generatorOptions:
  # disableNameSuffixHash is true disables the default behavior of adding a
  # suffix to the names of generated resources that is a hash of
  # the resource contents.
  disableNameSuffixHash: true

secretGenerator:
  - name: secret
    envs:
      - secrets.properties

configMapGenerator:
  - name: files
    files:
    - config.js
    - users.js
    - script.js
    - image.png
    - text.txt
